/* Generated By:JavaCC: Do not edit this line. ProjectGrammarConstants.java */
package Project;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjectGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PART = 5;
  /** RegularExpression Id. */
  int MEASURE = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int ATTRIBUTES = 8;
  /** RegularExpression Id. */
  int DIVISIONS = 9;
  /** RegularExpression Id. */
  int KEY = 10;
  /** RegularExpression Id. */
  int FIFTHS = 11;
  /** RegularExpression Id. */
  int TIME = 12;
  /** RegularExpression Id. */
  int BEATS = 13;
  /** RegularExpression Id. */
  int BEATTYPE = 14;
  /** RegularExpression Id. */
  int STAVES = 15;
  /** RegularExpression Id. */
  int CLEF = 16;
  /** RegularExpression Id. */
  int SIGN = 17;
  /** RegularExpression Id. */
  int LINE = 18;
  /** RegularExpression Id. */
  int NOTE = 19;
  /** RegularExpression Id. */
  int PITCH = 20;
  /** RegularExpression Id. */
  int STEP = 21;
  /** RegularExpression Id. */
  int OCTAVE = 22;
  /** RegularExpression Id. */
  int DURATION = 23;
  /** RegularExpression Id. */
  int TYPE = 24;
  /** RegularExpression Id. */
  int TYPEVALUE = 25;
  /** RegularExpression Id. */
  int NUMBER = 26;
  /** RegularExpression Id. */
  int ALPHABET = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"part\"",
    "\"measure\"",
    "\"print\"",
    "\"attributes\"",
    "\"divisions\"",
    "\"key\"",
    "\"fifths\"",
    "\"time\"",
    "\"beats\"",
    "\"beat-type\"",
    "\"staves\"",
    "\"clef\"",
    "\"sign\"",
    "\"line\"",
    "\"note\"",
    "\"pitch\"",
    "\"step\"",
    "\"octave\"",
    "\"duration\"",
    "\"type\"",
    "<TYPEVALUE>",
    "<NUMBER>",
    "<ALPHABET>",
    "\"<\"",
    "\">\"",
    "\"</\"",
  };

}
